import type { SampleMasterData } from "./schema";

/**
 * 開発時の疎通確認用サンプル。
 * DBの自動採番IDは持たず、関連は図鑑番号+フォルムまたは一意な名称で指定する。
 */
export const sampleMasterData = {
  pokemons: [
    {
      dexNo: 130,
      nameJa: "ギャラドス",
      nameEn: "Gyarados",
      form: "normal",
      type1: "water",
      type2: "flying",
      baseHp: 95,
      baseAtk: 125,
      baseDef: 79,
      baseSpa: 60,
      baseSpd: 100,
      baseSpe: 81,
      abilities: ["いかく", "じしんかじょう"],
      isMega: false,
      basePokemon: null,
    },
    {
      dexNo: 450,
      nameJa: "カバルドン",
      nameEn: "Hippowdon",
      form: "normal",
      type1: "ground",
      type2: null,
      baseHp: 108,
      baseAtk: 112,
      baseDef: 118,
      baseSpa: 68,
      baseSpd: 72,
      baseSpe: 47,
      abilities: ["すなおこし", "すなのちから"],
      isMega: false,
      basePokemon: null,
    },
    {
      dexNo: 887,
      nameJa: "ドラパルト",
      nameEn: "Dragapult",
      form: "normal",
      type1: "dragon",
      type2: "ghost",
      baseHp: 88,
      baseAtk: 120,
      baseDef: 75,
      baseSpa: 100,
      baseSpd: 75,
      baseSpe: 142,
      abilities: ["クリアボディ", "すりぬけ", "のろわれボディ"],
      isMega: false,
      basePokemon: null,
    },
    {
      dexNo: 130,
      nameJa: "メガギャラドス",
      nameEn: "Mega Gyarados",
      form: "mega",
      type1: "water",
      type2: "dark",
      baseHp: 95,
      baseAtk: 155,
      baseDef: 109,
      baseSpa: 70,
      baseSpd: 130,
      baseSpe: 81,
      abilities: ["かたやぶり"],
      isMega: true,
      basePokemon: { dexNo: 130, form: "normal" },
    },
  ],
  moves: [
    {
      nameJa: "たきのぼり",
      nameEn: "Waterfall",
      type: "water",
      category: "physical",
      power: 80,
      accuracy: 100,
      priority: 0,
      tags: [],
    },
    {
      nameJa: "かみくだく",
      nameEn: "Crunch",
      type: "dark",
      category: "physical",
      power: 80,
      accuracy: 100,
      priority: 0,
      tags: [],
    },
    {
      nameJa: "りゅうのまい",
      nameEn: "Dragon Dance",
      type: "dragon",
      category: "status",
      power: null,
      accuracy: null,
      priority: 0,
      tags: ["setup"],
    },
    {
      nameJa: "じしん",
      nameEn: "Earthquake",
      type: "ground",
      category: "physical",
      power: 100,
      accuracy: 100,
      priority: 0,
      tags: [],
    },
    {
      nameJa: "ステルスロック",
      nameEn: "Stealth Rock",
      type: "rock",
      category: "status",
      power: null,
      accuracy: null,
      priority: 0,
      tags: ["hazard"],
    },
    {
      nameJa: "あくび",
      nameEn: "Yawn",
      type: "normal",
      category: "status",
      power: null,
      accuracy: null,
      priority: 0,
      tags: ["status"],
    },
    {
      nameJa: "ドラゴンアロー",
      nameEn: "Dragon Darts",
      type: "dragon",
      category: "physical",
      power: 50,
      accuracy: 100,
      priority: 0,
      tags: [],
    },
    {
      nameJa: "とんぼがえり",
      nameEn: "U-turn",
      type: "bug",
      category: "physical",
      power: 70,
      accuracy: 100,
      priority: 0,
      tags: ["pivot"],
    },
  ],
  items: [
    {
      nameJa: "ギャラドスナイト",
      nameEn: "Gyaradosite",
      effectTags: ["mega_stone"],
    },
    {
      nameJa: "こだわりスカーフ",
      nameEn: "Choice Scarf",
      effectTags: ["choice", "speed_boost"],
    },
    {
      nameJa: "オボンのみ",
      nameEn: "Sitrus Berry",
      effectTags: ["berry", "recovery"],
    },
  ],
  abilities: [
    { nameJa: "いかく", nameEn: "Intimidate", effectTags: ["stat_control"] },
    { nameJa: "じしんかじょう", nameEn: "Moxie", effectTags: ["stat_control"] },
    { nameJa: "かたやぶり", nameEn: "Mold Breaker", effectTags: [] },
    { nameJa: "すなおこし", nameEn: "Sand Stream", effectTags: ["weather"] },
    {
      nameJa: "すなのちから",
      nameEn: "Sand Force",
      effectTags: ["weather", "damage_boost"],
    },
    { nameJa: "クリアボディ", nameEn: "Clear Body", effectTags: ["stat_control"] },
    { nameJa: "すりぬけ", nameEn: "Infiltrator", effectTags: [] },
    { nameJa: "のろわれボディ", nameEn: "Cursed Body", effectTags: [] },
  ],
  pokemonMoves: [
    {
      pokemon: { dexNo: 130, form: "normal" },
      moveNameEn: "Waterfall",
    },
    {
      pokemon: { dexNo: 130, form: "normal" },
      moveNameEn: "Crunch",
    },
    {
      pokemon: { dexNo: 130, form: "normal" },
      moveNameEn: "Dragon Dance",
    },
    {
      pokemon: { dexNo: 130, form: "mega" },
      moveNameEn: "Waterfall",
    },
    {
      pokemon: { dexNo: 130, form: "mega" },
      moveNameEn: "Crunch",
    },
    {
      pokemon: { dexNo: 450, form: "normal" },
      moveNameEn: "Earthquake",
    },
    {
      pokemon: { dexNo: 450, form: "normal" },
      moveNameEn: "Stealth Rock",
    },
    {
      pokemon: { dexNo: 450, form: "normal" },
      moveNameEn: "Yawn",
    },
    {
      pokemon: { dexNo: 887, form: "normal" },
      moveNameEn: "Dragon Darts",
    },
    {
      pokemon: { dexNo: 887, form: "normal" },
      moveNameEn: "U-turn",
    },
  ],
  seasons: [
    {
      name: "開発サンプルシーズン",
      startsAt: "2026-07-01",
      endsAt: "2026-09-30",
    },
  ],
  rules: [
    {
      name: "シングルバトル（6体から3体選出）",
      teamSize: 6,
      pickSize: 3,
    },
  ],
} satisfies SampleMasterData;
